### ISSUE TITLE
duplicate keys in deployment/init.sql for type activities

### ISSUE THREAD

**Issue by mavoll** [sidewalklabs/commonspace#18]
duplicate keys in deployment/init.sql:

Double mentioned:
 
'recreation_active',
'recreation_passive',

resulting in:
duplicate key value violates unique constraint "pg_enum_typid_label_index"

**Comment by mavoll** [comment]
Also during installation I needed to set absolute paths for:

"sql_init_file":    in    postgrees.json

and

packer build *absolute*/postgres.json  in develop.sh

**Comment by californianseabass** [comment]
thanks for the issues! these two have been fixed by updating https://github.com/sidewalklabs/commonspace/blob/master/CONTRIBUTING.md and removing the extraneous lines in deployment/init.sql
