### ISSUE TITLE
Clicking outside of create study window

### ISSUE THREAD

**Issue by sdotdata** [sidewalklabs/commonspace#21]
Accidentally clicked outside of the pop up window when creating a study, and it deleted all my progress. Suggest auto-saving, or asking user if they are sure they want to exit.

**Comment by mebreuer** [comment]
Hey Alex - thanks for filing this issue! It's similar to issue #9 so I'm going to close this issue and paste your note as a comment in that issue. Would also invite you to add an upvote there. Thanks
